"""add encoder columns to render_jobs

Records the CPU/GPU encoder choice per render job (v1.2).

Every column is NOT NULL, so each one carries a server_default. Autogenerate
omits those, which would make this migration fail on any database that already
has render_jobs rows — existing rows have no value to put in a NOT NULL column.
Historic jobs are backfilled as CPU renders, which is what they were.

Revision ID: 92dae0b434f1
Revises: f139cbb1f257
Create Date: 2026-08-01 03:02:14.325362
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '92dae0b434f1'
down_revision: str | None = 'f139cbb1f257'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('render_jobs', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'encoder_requested', sa.String(length=20),
                nullable=False, server_default='auto',
            )
        )
        # Existing rows predate GPU support, so they were CPU renders.
        batch_op.add_column(
            sa.Column('encoder', sa.String(length=20), nullable=False, server_default='cpu')
        )
        batch_op.add_column(
            sa.Column(
                'encoder_hardware', sa.Boolean(),
                nullable=False, server_default=sa.false(),
            )
        )
        batch_op.add_column(
            sa.Column(
                'encoder_fell_back', sa.Boolean(),
                nullable=False, server_default=sa.false(),
            )
        )
        batch_op.add_column(
            sa.Column('encoder_reason', sa.Text(), nullable=False, server_default='')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('render_jobs', schema=None) as batch_op:
        batch_op.drop_column('encoder_reason')
        batch_op.drop_column('encoder_fell_back')
        batch_op.drop_column('encoder_hardware')
        batch_op.drop_column('encoder')
        batch_op.drop_column('encoder_requested')

    # ### end Alembic commands ###
