"""initial schema v1.0

Revision ID: c1cd8f18e5a6
Revises:
Create Date: 2026-07-31 23:09:05.637088
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'c1cd8f18e5a6'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('workspaces',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspaces_owner_id'), ['owner_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('manhwa_title', sa.String(length=200), nullable=False),
    sa.Column('chapter', sa.String(length=60), nullable=False),
    sa.Column('content_type', sa.String(length=40), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('spoiler_level', sa.String(length=20), nullable=False),
    sa.Column('narration_style', sa.String(length=20), nullable=False),
    sa.Column('target_duration', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('series_name', sa.String(length=200), nullable=False),
    sa.Column('cta_text', sa.Text(), nullable=False),
    sa.Column('banned_words', sa.JSON(), nullable=False),
    sa.Column('pronunciations', sa.JSON(), nullable=False),
    sa.Column('voice_id', sa.String(length=80), nullable=False),
    sa.Column('template', sa.String(length=60), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('youtube_channels',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('channel_id', sa.String(length=120), nullable=False),
    sa.Column('channel_title', sa.String(length=200), nullable=False),
    sa.Column('encrypted_credentials', sa.Text(), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('youtube_channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_youtube_channels_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('quality_checks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=False),
    sa.Column('overridden_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quality_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quality_checks_project_id'), ['project_id'], unique=False)

    op.create_table('render_jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=80), nullable=False),
    sa.Column('output_key', sa.String(length=500), nullable=False),
    sa.Column('subtitle_key', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_key', sa.String(length=500), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('log_tail', sa.Text(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('render_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_render_jobs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_render_jobs_status'), ['status'], unique=False)

    op.create_table('script_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('hook_options', sa.JSON(), nullable=False),
    sa.Column('selected_hook', sa.Integer(), nullable=False),
    sa.Column('estimated_duration', sa.Float(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('generator', sa.String(length=40), nullable=False),
    sa.Column('approved_by', sa.String(length=32), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version', name='uq_script_project_version')
    )
    with op.batch_alter_table('script_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_script_versions_project_id'), ['project_id'], unique=False)

    op.create_table('source_assets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('rights_owner', sa.String(length=255), nullable=False),
    sa.Column('license_type', sa.String(length=40), nullable=False),
    sa.Column('permission_reference', sa.Text(), nullable=False),
    sa.Column('permission_date', sa.String(length=40), nullable=False),
    sa.Column('usage_limits', sa.Text(), nullable=False),
    sa.Column('rights_status', sa.String(length=20), nullable=False),
    sa.Column('attribution', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_assets_checksum'), ['checksum'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_assets_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_assets_rights_status'), ['rights_status'], unique=False)

    op.create_table('story_analyses',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('characters', sa.JSON(), nullable=False),
    sa.Column('locations', sa.JSON(), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('main_conflict', sa.Text(), nullable=False),
    sa.Column('twist', sa.Text(), nullable=False),
    sa.Column('cliffhanger', sa.Text(), nullable=False),
    sa.Column('pronunciation_candidates', sa.JSON(), nullable=False),
    sa.Column('low_confidence_notes', sa.JSON(), nullable=False),
    sa.Column('edited_by_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('story_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_story_analyses_project_id'), ['project_id'], unique=False)

    op.create_table('subtitle_cues',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('edited_by_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subtitle_cues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subtitle_cues_project_id'), ['project_id'], unique=False)

    op.create_table('audio_segments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('script_version_id', sa.String(length=32), nullable=False),
    sa.Column('section', sa.String(length=20), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('voice_id', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('word_timings', sa.JSON(), nullable=False),
    sa.Column('user_uploaded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['script_version_id'], ['script_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audio_segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audio_segments_script_version_id'), ['script_version_id'], unique=False)

    op.create_table('publications',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('render_job_id', sa.String(length=32), nullable=True),
    sa.Column('channel_id', sa.String(length=32), nullable=True),
    sa.Column('youtube_video_id', sa.String(length=40), nullable=False),
    sa.Column('video_title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('privacy_status', sa.String(length=20), nullable=False),
    sa.Column('upload_status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['youtube_channels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['render_job_id'], ['render_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publications_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_publications_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publications_upload_status'), ['upload_status'], unique=False)

    op.create_table('timeline_scenes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('focus_x', sa.Float(), nullable=False),
    sa.Column('focus_y', sa.Float(), nullable=False),
    sa.Column('effect', sa.String(length=40), nullable=False),
    sa.Column('overlay_text', sa.Text(), nullable=False),
    sa.Column('transition', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['source_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timeline_scenes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timeline_scenes_project_id'), ['project_id'], unique=False)

    op.create_table('video_stats',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('publication_id', sa.String(length=32), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('average_view_duration', sa.Float(), nullable=False),
    sa.Column('average_percentage_viewed', sa.Float(), nullable=False),
    sa.Column('subscribers_gained', sa.Integer(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('video_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_stats_publication_id'), ['publication_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_stats_publication_id'))

    op.drop_table('video_stats')
    with op.batch_alter_table('timeline_scenes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timeline_scenes_project_id'))

    op.drop_table('timeline_scenes')
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publications_upload_status'))
        batch_op.drop_index(batch_op.f('ix_publications_project_id'))
        batch_op.drop_index(batch_op.f('ix_publications_idempotency_key'))

    op.drop_table('publications')
    with op.batch_alter_table('audio_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audio_segments_script_version_id'))

    op.drop_table('audio_segments')
    with op.batch_alter_table('subtitle_cues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subtitle_cues_project_id'))

    op.drop_table('subtitle_cues')
    with op.batch_alter_table('story_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_story_analyses_project_id'))

    op.drop_table('story_analyses')
    with op.batch_alter_table('source_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_assets_rights_status'))
        batch_op.drop_index(batch_op.f('ix_source_assets_project_id'))
        batch_op.drop_index(batch_op.f('ix_source_assets_checksum'))

    op.drop_table('source_assets')
    with op.batch_alter_table('script_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_script_versions_project_id'))

    op.drop_table('script_versions')
    with op.batch_alter_table('render_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_render_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_render_jobs_project_id'))

    op.drop_table('render_jobs')
    with op.batch_alter_table('quality_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quality_checks_project_id'))

    op.drop_table('quality_checks')
    with op.batch_alter_table('youtube_channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_youtube_channels_workspace_id'))

    op.drop_table('youtube_channels')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_projects_status'))

    op.drop_table('projects')
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspaces_owner_id'))

    op.drop_table('workspaces')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
