"""add provider_credentials for BYOK

Adds the v1.1 bring-your-own-key table. Purely additive: no existing table is
touched, so upgrading a v1.0 database cannot lose data.

WARNING: the downgrade drops the table, which permanently destroys every stored
API key (they are encrypted, not recoverable from anywhere else). Users would
have to paste their keys in again. Back up ``data/manhwashorts.db`` first.

Revision ID: f139cbb1f257
Revises: c1cd8f18e5a6
Create Date: 2026-08-01 01:59:08.019819
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'f139cbb1f257'
down_revision: str | None = 'c1cd8f18e5a6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_credentials',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('encrypted_secret', sa.Text(), nullable=False),
    sa.Column('key_hint', sa.String(length=12), nullable=False),
    sa.Column('base_url', sa.String(length=300), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('available_models', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_message', sa.Text(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'kind', 'provider', name='uq_credential_scope')
    )
    with op.batch_alter_table('provider_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_credentials_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_credentials_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_credentials_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_provider_credentials_kind'))

    op.drop_table('provider_credentials')
    # ### end Alembic commands ###
